### ISSUE TITLE
fatal error: alsa/asoundlib.h: No such file or directory

### ISSUE THREAD

**Issue by adhirmndl** [OtherCrashOverride/c2play#36]
odroid@odroid:~/ivis-codec/c2play$ make
==== Building c2play (debug) ====
Creating obj/Debug/c2play
main.cpp
../../src/main.cpp:24:10: fatal error: alsa/asoundlib.h: No such file or directory
 #include <alsa/asoundlib.h>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
c2play.make:163: recipe for target 'obj/Debug/c2play/main.o' failed
make[1]: *** [obj/Debug/c2play/main.o] Error 1
Makefile:16: recipe for target 'c2play' failed
make: *** [c2play] Error 2

**Comment by OtherCrashOverride** [comment]
Consult the README for the required dependencies:
https://github.com/OtherCrashOverride/c2play/blob/master/README

**Comment by adhirmndl** [comment]
sudo apt install libasound2-dev libavformat-dev libass-dev

installed .. 


next Error
/usr/include/EGL/eglplatform.h:125:10: fatal error: X11/Xlib.h: No such file or directory
 #include <X11/Xlib.h>


Please help ..

**Comment by adhirmndl** [comment]
odroid@odroid:~/c2play$ cd /usr/lib/aml_libs/
odroid@odroid:/usr/lib/aml_libs$ ls
libadpcm.so  libamadec.so  libamavutils.so  libamcodec.so  libamr.so  libape.so  libcook.so  libfaad.so  libflac.so  liblibpcm_wfd.so  libmad.so  libpcm.so  libraac.so


libasound.so   -- is missing.. Please help

**Comment by OtherCrashOverride** [comment]
To build the x11 version, the xorg-dev package is also required.

libasound.so is provided by the libasound2-dev package as a dependency of it.  The build is testing and works with HardKernel's official Ubuntu 16.04 or Ubuntu 18.04 (bionic branch).  Other distributions or environments are not supported (by me).
